[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/public/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"


[[redirects]]
  from = "/style/*"
  to = "/public/style/:splat"
  status = 200
