[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/style/*"
  to = "/public/style/:splat"
  status = 200

[[redirects]]
  from = "/script/*"
  to = "/public/script/:splat"
  status = 200

[[redirects]]
  from = "/img/*"
  to = "/public/img/:splat"
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/public/uploads/:splat"
  status = 200
